In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns  # visualization tool
from subprocess import check_output
#print(check_output(["ls", "../input"]).decode("utf8"))
data = pd.read_csv('AI_phase3dataset.csv')
#data.info()
data.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Magnitude Type,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,10/27/2016,11:53:17,53.5855,-163.2650,Earthquake,13.89,3.3,MWW,0.071,17.0,68.0,1.276,6.9,0.97,US100072BS,US,US,US,Reviewed
1,10/27/2016,20:32:56,-33.7771,-72.5321,Earthquake,12.57,2.7,MWW,0.071,17.0,78.0,0.774,4.2,1.05,US100072GN,US,US,US,Reviewed
2,10/28/2016,5:26:56,-4.6721,153.2156,Earthquake,45.15,4.4,MWW,0.071,17.0,26.0,1.152,6.2,0.92,US100072JV,US,US,US,Reviewed
3,10/28/2016,20:02:50,39.3881,13.5205,Earthquake,457.86,3.6,MWW,0.071,17.0,17.0,1.822,8.0,0.76,US100072SU,US,US,US,Reviewed
4,10/30/2016,6:40:19,42.8621,13.0961,Earthquake,8.00,1.8,MWW,0.071,17.0,25.0,0.174,5.3,0.67,US1000731J,US,US,US,Reviewed

In [2]:
data.tail()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Magnitude Type,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
98,12/28/2016,8:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,ML,0.320,266.0,42.47,0.120,NaN,0.1898,NN00570710,NN,NN,NN,Reviewed
99,12/28/2016,9:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,ML,0.260,266.0,48.58,0.129,NaN,0.2187,NN00570744,NN,NN,NN,Reviewed
100,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,MWW,0.048,266.0,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed
101,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,MWW,0.048,266.0,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed
102,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,MB,0.029,266.0,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed

In [3]:
data.columns

Index(['Date', 'Time', 'Latitude', 'Longitude', 'Type', 'Depth', 'Depth Error',
       'Magnitude Type', 'Magnitude Error', 'Magnitude Seismic Stations',
       'Azimuthal Gap', 'Horizontal Distance', 'Horizontal Error',
       'Root Mean Square', 'ID', 'Source', 'Location Source',
       'Magnitude Source', 'Status'],
      dtype='object')

In [4]:
data.shape

(103, 19)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        103 non-null    object
 1   Time                        103 non-null    object
 2   Latitude                    103 non-null    float64
 3   Longitude                   103 non-null    float64
 4   Type                        103 non-null    object
 5   Depth                       103 non-null    float64
 6   Depth Error                 103 non-null    float64
 7   Magnitude Type              103 non-null    object
 8   Magnitude Error             103 non-null    float64
 9   Magnitude Seismic Stations  102 non-null    float64
 10  Azimuthal Gap               103 non-null    float64
 11  Horizontal Distance         103 non-null    float64
 12  Horizontal Error            100 non-null    float64
 13  Root Mean Square            103 non-null    float64
 14  ID                          103 non-null    object
 15  Source                      103 non-null    object
 16  Location Source             103 non-null    object
 17  Magnitude Source            103 non-null    object
 18  Status                      103 non-null    object
dtypes: float64(10), object(9)
memory usage: 15.4+ KB